---
title: "R Notebook"
output:
  html_document:
    df_print: paged
  html_notebook: default
  pdf_document: default
---

## Importing the data

```{r}
library(ggplot2)
library(dplyr)
library(ggthemes)
```

```{r}
titanic = read.csv(file = "data/train.csv", header = TRUE)
titanic$Pclass <- factor(titanic$Pclass)
titanic$Survived <- factor(titanic$Survived)
```

```{r}
str(titanic)
```

## Bar charts to describe gender, ticket class, and survival of passengers
### Gender
```{r}
gender_bars <- ggplot(titanic) + geom_bar(aes(x = Sex, fill = Sex)) +
  labs(title="Passenger Count by Gender", y = "Passenger Count") + theme_classic()
gender_bars
```

### Ticket Class
```{r}
class_bars <- ggplot(titanic) + geom_bar(aes(x = Pclass, fill=Pclass)) +
  labs(title = "Passenger Count by Ticket Class", y = "Passenger Count") + theme_classic()
class_bars
```

### Survival
```{r}
survival_bars <- ggplot(titanic) + geom_bar(aes(x = Survived, fill=Survived)) +
  labs(title="Passenger Survival Counts", y = "Passenger Count") + theme_light()
survival_bars
```
## Passenger Age Distribution
### Histoogram of Passenger Age
```{r}
age_hist <- ggplot(titanic %>% drop_na(Age)) +
  geom_histogram(aes(x = Age), binwidth = 5) +
  labs(title="Passenger Age") + theme_bw()
age_hist
```
### Age per Ticket Class
```{r}
age_class_boxplot <- ggplot(titanic %>% drop_na(Age)) + geom_boxplot(aes(x=Pclass, y=Age))
age_class_boxplot
```
### Age per Survival
```{r}
age_survival_boxplot <- ggplot(titanic %>% drop_na(Age)) + geom_boxplot(aes(x=Survived, y=Age))
age_survival_boxplot
```

## Travel Fares
```{r}
fares_hist <- ggplot(titanic) + geom_histogram(aes(x = Fare), binwidth = 10)
fares_hist
```
```{r}
titanic %>% filter(Fare == 0)
```

## Family Size
```{r}
titanic$Family <- titanic$SibSp + titanic$Parch
```

```{r}
ggplot(titanic) +
  geom_boxplot(aes(y = Family)) +
  facet_grid(~Pclass) +
  labs(title = "Family Size by Ticket Class", y="Family Size") +
  theme_solarized()
```

## Gender & Ticket Class
```{r}
ggplot(titanic) +
  geom_bar(aes(x = Sex, fill=Survived), position = "stack") +
  facet_grid(~Pclass) +
  labs(title="Passenger Count by Ticket Class & Gender", y = "Passenger Count") +
  theme_wsj()
```